// constants.ts
import { ColorMapping } from '@/components/Balloon/types';

export const phonemes: string[] = [
  'P',
  'L',
  'K',
  'T',
  'S',
  'CH',
  'LH',
  'F',
  'B',
  'N',
  'G',
  'D',
  'Z',
  'J',
  'NH',
  'V',
  'M',
  'R',
  'ARQ',
  'C/R/V',
  'C/L/V',
  'Vogais',
];

export const balloonColors: string[] = [
  '#6366f1',
  '#8b5cf6',
  '#ec4899',
  '#f59e0b',
  '#10b981',
  '#3b82f6',
  '#a855f7',
  '#f43f5e',
  '#14b8a6',
  '#84cc16',
  '#06b6d4',
  '#7c3aed',
  '#e879f9',
  '#fbbf24',
  '#22d3ee',
  '#c084fc',
  '#fb923c',
  '#34d399',
  '#a78bfa',
  '#059669',
  '#f472b6',
  '#4ade80',
  '#2dd4bf',
];

export const colorNames: ColorMapping = {
  '#6366f1': 'Indigo',
  '#8b5cf6': 'Violet',
  '#ec4899': 'Pink',
  '#f59e0b': 'Amber',
  '#10b981': 'Emerald',
  '#3b82f6': 'Blue',
  '#a855f7': 'Purple',
  '#f43f5e': 'Rose',
  '#14b8a6': 'Teal',
  '#84cc16': 'Lime',
  '#06b6d4': 'Cyan',
  '#7c3aed': 'Violet Dark',
  '#e879f9': 'Fuchsia',
  '#fbbf24': 'Gold',
  '#22d3ee': 'Sky',
  '#c084fc': 'Lavender',
  '#fb923c': 'Orange',
  '#34d399': 'Mint',
  '#a78bfa': 'Light Purple',
  '#059669': 'Green',
  '#f472b6': 'Light Pink',
  '#4ade80': 'Light Green',
  '#2dd4bf': 'Aqua',
};

export const PHONEME_MESSAGES: { [key: string]: string } = {
  P: 'Fonema bilabial. Palavras: pato, pipoca, sapato.',
  B: 'Fonema bilabial sonoro. Palavras: bola, bebê, cabelo.',
  T: 'Fonema dental. Palavras: tatu, tomate, prato.',
  D: 'Fonema dental sonoro. Palavras: dado, dedo, cadeira.',
  K: 'Fonema velar. Palavras: casa, macaco, foca.',
  G: 'Fonema velar sonoro. Palavras: gato, fogão, lago.',
  F: 'Fonema labiodental. Palavras: faca, café, elefante.',
  V: 'Fonema labiodental sonoro. Palavras: vaca, uva, cavalo.',
  S: 'Fonema alveolar. Palavras: sapo, pássaro, laço.',
  Z: 'Fonema alveolar sonoro. Palavras: zebra, casa, azar.',
  CH: 'Fonema palatal. Palavras: chave, chuva, bicho.',
  J: 'Fonema palatal sonoro. Palavras: jogo, queijo, girafa.',
  LH: 'Fonema lateral palatal. Palavras: palhaço, orelha, milho.',
  NH: 'Fonema nasal palatal. Palavras: ninho, banho, galinha.',
  L: 'Fonema lateral. Palavras: lua, bola, palma.',
  R: 'Fonema vibrante. Palavras: rato, carro, porta.',
  M: 'Fonema nasal bilabial. Palavras: mão, cama, campo.',
  N: 'Fonema nasal alveolar. Palavras: nariz, cana, pente.',
  ARQ: 'Encontros com arquifonemas. Palavras: carta, porta, verde.',
  'C/R/V': 'Encontro consonantal com R. Palavras: prato, braço, cravo.',
  'C/L/V': 'Encontro consonantal com L. Palavras: planta, blusa, flor.',
  Vogais: 'Vogais orais e nasais. Palavras: abelha, escola, urubu.',
};
